# Generated by Django 4.0.3 on 2022-04-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_eight_aadhar_no_eight_admission_date_eight_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eight',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fifth',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='first',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fourth',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='nineth',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='second',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='seventh',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sixth',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tenth',
            name='admission_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='third',
            name='admission_date',
            field=models.DateField(),
        ),
    ]
