# Generated by Django 4.0.3 on 2022-04-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_eight_std_fifth_std_first_std_fourth_std_nineth_std_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
