# Generated by Django 4.0.3 on 2022-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_eight_birth_date_eight_birth_place_eight_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='first',
            name='birth_date',
            field=models.DateField(verbose_name='Enter date'),
        ),
    ]
