# Generated by Django 4.0.3 on 2022-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_remove_eight_total_bus_fees_remain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eight',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eight',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleventh',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eleventh',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fifth',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fifth',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='first',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourth',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fourth',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkg',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lkg',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nineth',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nineth',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrs',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrs',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='second',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='second',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seventh',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seventh',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sixth',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sixth',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenth',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenth',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='third',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='third',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelth',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twelth',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ukg',
            name='total_bus_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ukg',
            name='total_school_fees_remain',
            field=models.CharField(default=1, max_length=17),
            preserve_default=False,
        ),
    ]
